/*****************************************
 * Defines for  ISVGA256.BGI   driver     *
 *                                       *
 * Auto Detect defines for ATI, VID7,    *
 * TECMAR, Tseng Labs, and Paradise      *
 *                                       *
 * 891005  Thomas Design                 *
 *****************************************/

extern int huge _Cdecl DetectISVGA256(void);


